environment:
  nodejs_version: "18" # окружение
branches:
  only:
    - main # ветка git
cache: node_modules # кеширование
install:
  - yarn add --dev package.json # команда установки зависимостей
build: off
build_script:
  - yarn run build # скрипт сборки
test_script:
  - yarn run lint  # скрипт прверки