image: Ubuntu1804 # образ для сборки
stack: node 20 # окружение
branches:
  only:
    - main # ветка git
cache: node_modules # кеширование
install:
  - yarn # команда установки зависимостей
build: off
build_script:
  - yarn run build # скрипт сборки
test_script:
  - yarn run lint  # скрипт прверки